### ISSUE TITLE
[FEATURE] Click to focus in barcode view

### ISSUE THREAD

**Issue by hsson** [brightec/KBarcode#11]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Rather than relying autofocus, it would be nice to allow the user to click within the view to focus.

**Describe alternatives you've considered**
None really..

**Additional context**
None

**Comment by alistairsykes** [comment]
Nice idea! I did consider this during the development, but given my timeframe had to drop it in favour of auto focus. Maybe this is one to re-visit.

If others could give this issue a +1 if this is a feature you would use.

**Comment by jonatandorozco** [comment]
+1

**Comment by MJ-BH** [comment]
+1

**Comment by iTruff** [comment]
+1

**Comment by JoeM88** [comment]
+1

**Comment by alistairsykes** [comment]
Will be included in the next release
