### ISSUE TITLE
[BUG] Samsung Galaxy S9

### ISSUE THREAD

**Issue by alorma** [brightec/KBarcode#16]
**Describe the bug**

On Samsung Galaxy S9 device, camera is not even started and activity gets stuck

**To Reproduce**
1. Implement on Galaxy S9

**Expected behavior**
Camera preview is shown and able to scan

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 9
 - Version 1.0.3

**Comment by alistairsykes** [comment]
Hi @alorma,

Sorry I wasn't able to get to this sooner. Given you have closed this issue, have you solved the problem?

**Comment by alorma** [comment]
Yes, it looked like i was not closing the camera , or it was stuck somehow... reseting my phone solved the problem :P
