### ISSUE TITLE
[QUESTION] - minSDK

### ISSUE THREAD

**Issue by TurKurT656** [brightec/KBarcode#18]
TnQ for this great lib.
however when i want to add this lib it gives me this build failure:
```
Manifest merger failed : uses-sdk:minSdkVersion 18 cannot be smaller than version 21 declared in library [uk.co.brightec.kbarcode:kbarcode:1.0.3] C:\Users\satari-s\.gradle\caches\transforms-2\files-2.1\a77019e964680a36c49ac5f39ad6b767\AndroidManifest.xml as the library might be using APIs not available in 18
	Suggestion: use a compatible library with a minSdk of at most 18,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="uk.co.brightec.kbarcode" to force usage (may lead to runtime failures)
```

Is it possible to decrease the min sdk version?

**Comment by alistairsykes** [comment]
This library is based on the camera2 APIs. I'm afraid these APIs have a min SDK requirement of 21. So unfortunately if you need min SDK 18 for your project then you won't be able to use this library solely. 

You could either use it for some users, or in combination with another library which uses camera1 APIs. 
The camera1 APIs are deprecated, but still supported in newer versions of Android, so if you only wanted to implement one library then you would need one which uses those.

Link to more information about this project:
https://github.com/brightec/KBarcode/wiki/Under-the-Hood
