### ISSUE TITLE
RTFM: Does this lib support QrCode?

### ISSUE THREAD

**Issue by mrahimygk** [brightec/KBarcode#20]
The title describes itself: I can't find an option in app:format for QR Codes.

**Comment by alistairsykes** [comment]
Hi @m-rahimy,

Within XML there is support for a few groups of formats. Or if you want one specific one, or a different group or formats, you need to specify programmatically. See [wiki page](https://github.com/brightec/KBarcode/wiki/Reference#barcode-formats) for more detail and an example block of code. It sounds like for your case you'd want something like:
```
barcodeView.setBarcodeFormats(
  intArrayOf(
    Barcode.FORMAT_QR_CODE
  )
)
```

https://github.com/brightec/KBarcode/wiki/Reference#barcode-formats
