### ISSUE TITLE
[FEATURE] Add a way to pause the camera preview, or clear the list of scanned barcodes.

### ISSUE THREAD

**Issue by maartenvang** [brightec/KBarcode#24]
Right now, calling `barcodeView.start()` or `lifecycle.addObserver(barcodeView)` starts the camera preview. Calling `barcodeView.pause()` does pause the barcode scanning, but not the preview. In order to actually pause the view, I have to call `barcodeView.release()`. This kinda works, but when starting the barcode view again, the onBarcodeListener gets called with the previous scanned value instantly.

**Describe the solution you'd like**
It would be great to have a way to stop the preview and barcode scanning altogether, and restart it later, without it firing the onBarcodeListener when resuming.

That would be possible through a `pausePreview()` and `resumePreview` method I suppose.

**Comment by alistairsykes** [comment]
Super interesting use case. I'd never considered wanting to pause the preview.

I think given the nature of library, I'm not sure that having a `pausePreview()` would really fit, and I think to achieve this release and start is the right approach. However I do think that releasing and starting shouldn't re-yield the previous barcodes.

I think the potential solution here is to clear the value from the LiveData whenever `release()` is called. I'm not sure yet if this should happen in `BarcodeScanner` or `BarcodeProcessorSingle`. That should mean that you could continue with your approach, do you think that would work for you @maartenvang ?

**Comment by maartenvang** [comment]
Hi @alistairsykes , thanks for the swift reply.
I wasn't sure whether to report a bug for the re-yielding of the previous barcodes, or to add a feature request to pause / restart the preview. I went for the first one, but perhaps a bug should have been better.

I think that clearing the scanned barcodes in `release()` already fixes the issues I'm having, whilst not being a breaking change. Only, calling `release()` to pause the preview sounds scary when you still intend to use the same barcodeView, but it seems safe to do so.

**Comment by alistairsykes** [comment]
Sorry the language does make it sound scary, but I just inherited that from the camera api's. It should be safe to do so. If you see any issues with that do report them.

Thanks for reporting this one. It's just not a case I'd really thought about.

I will try to work on a fix for this as soon as I can.

**Comment by alistairsykes** [comment]
Released https://github.com/brightec/KBarcode/releases/tag/v1.1.0
