### ISSUE TITLE
The image quality is fairly poor.

### ISSUE THREAD

**Issue by bipinbharti1357** [brightec/KBarcode#27]
Image quality very poor while scan barcode.
Any Solution?
Why does this thing happen
![2019-11-28](https://user-images.githubusercontent.com/14543391/69849717-78919f00-12a3-11ea-87d6-c2982ec6fef2.png)
?

**Comment by alistairsykes** [comment]
I'm afraid I don't think there is anything I can do about image quality for a specific device. 

Take a look through the source code and you can see I use the bare minimum of the camera2 api. You may be able to make very specific improvements for your device, but those will, all most certainly, not apply to all devices.

If you do spot anything specific that would be a general improvement, do let me know.
