### ISSUE TITLE
[FEATURE] Toggle flash on/off

### ISSUE THREAD

**Issue by shepardm7** [brightec/KBarcode#28]
For low-light situations I was thinking of implementing a button to turn the **flash** on/off but I couldn't find a way to do it in the library. And from what I know, I can't turn the flash on separately if there's already a camera instance running. So, having this feature built into it could've really helped.

**Comment by alistairsykes** [comment]
Nice feature request. There isn't currently a way, so adding this would be good.
Open to PR's for this.

**Comment by alistairsykes** [comment]
Will be included in the next release
