### ISSUE TITLE
How to capture or retreive the Image frame being scanned

### ISSUE THREAD

**Issue by mrcodecloud** [brightec/KBarcode#37]
I want to preview or store the image that was used for scanning. Therefore I want to get scanned image along with the result code, is there any way I can get that? 
Thanks for the support in advance.

**Comment by alistairsykes** [comment]
I'm afraid not. I have not built the library to provide back the image. 
I think it's unlikely that I would build this feature into the library.

I'd suggest using this libraries code to build your own solution. Or utilise [CameraX](https://developer.android.com/training/camerax).
This section of the [Wiki](https://github.com/brightec/KBarcode/wiki/Under-the-Hood) should help explain how the library works and give you some help to roll your own.
Specifically this [line](https://github.com/brightec/KBarcode/blob/master/kbarcode/src/main/java/uk/co/brightec/kbarcode/BarcodeScanner.kt#L190) is where you would acquire the image.

**Comment by mrcodecloud** [comment]
Respected @alistairsykes 
I retrieved the scanned image frame by using Interfaces, 
I used one interface for retrieving the frame bitmap from BarcodeScanner.kt back to BarcodeView.kt 
and another interface for retrieving the frame bitmap from BarcodeView.kt back to my Fragment class where I was calling barcodeview object for starting the processing. 
If you like, I will love to share my contribution. Thanks
Warm Regards,

**Comment by alistairsykes** [comment]
Amazing @RAZA-ABBBASI . Well done. 

Definitely share any code on this issue, as it might help someone who wants to do the same thing. I'd also be curious to see how you did it.
