### ISSUE TITLE
[FEATURE] FirebaseVisionBarcode is deprecated, migrate to ML Kit SDK

### ISSUE THREAD

**Issue by blazingcayenne** [brightec/KBarcode#39]
**Describe the solution you'd like**

The [FirebaseVisionBarcode](https://firebase.google.com/docs/reference/android/com/google/firebase/ml/vision/barcode/FirebaseVisionBarcode) class is deprecated. Google states:

> The standalone ML Kit SDK replaces this API. For more information, refer to the [migration](https://developers.google.com/ml-kit/migration) guide.

Do you have plans to migrate your very well designed library?

**Describe alternatives you've considered**

I have considered the following alternatives if Brightec does not plan to do this migration.

- Updating the library myself.
- Using the ML Kit SDK instead of the KBarcode library.

**Comment by alistairsykes** [comment]
Hi @blazingcayenne 

Sorry it's taken a while to get back to you on this issue. I am currently working on migrating this over to MLKit. Hopefully have a release soon.

**Comment by alistairsykes** [comment]
Will be included in the next release
