### ISSUE TITLE
[BUG] Black bar on the right

### ISSUE THREAD

**Issue by vyakhirev** [brightec/KBarcode#40]
**Describe the bug**
Black bar on the right

**To Reproduce**
Scan one barcode

**Screenshots**
https://i.imgur.com/fyEbSLL.png

**Smartphone (please complete the following information):**
https://i.imgur.com/mErv4cU.png

**Comment by alistairsykes** [comment]
Hi @vyakhirev 

I haven't been able to replicate this issue. Have you tried running the sample app and seeing if that has the same issue?
This could be a device specific bug which would need to be raised with Android Camera2.
